<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Basilisk</name>
    </assembly>
    <members>
        <member name="T:Global.BHoM_Object">
            <summary>
            BHoM Object
            </summary>
        </member>
        <member name="M:Global.BHoM_Object.SetPropertyValueByName(System.Object,System.String,System.Object)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.GetPropertyValueByName(System.Object,System.String)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.GetPropertyNames(System.Object)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.ToJSON(System.Object)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.FromJSON(System.String)">
            <summary></summary>
        </member>
        <member name="T:Structural.Bar">
            <summary>
            Structural tools
            BuroHappold
            <class name="BHGeometryTools">Geometry tools for Dynamo</class>
            </summary>
        </member>
        <member name="M:Structural.Bar.FromNodes(BHoM.Structural.Node,BHoM.Structural.Node)">
            <summary></summary>
        </member>
        <member name="T:Structural.Node">
            <summary></summary>
        </member>
        <member name="M:Structural.Node.FromDSPoint(Autodesk.DesignScript.Geometry.Point)">
            <summary></summary>
        </member>
        <member name="M:Structural.FormFinding.CustomRenderExample.Create(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Create an object which renders custom geometry.
            </summary>
        </member>
        <member name="T:Structural.FormFinding.DynamicRelaxation_BHoMEngine">
            <summary>
            Structural tools
            BuroHappold
            <class name="BHGeometryTools">Geometry tools for Dynamo</class>
            </summary>
        </member>
        <member name="M:Structural.FormFinding.DynamicRelaxation_BHoMEngine.RelaxLines(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line},System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Point},System.Collections.Generic.List{System.Double},System.Collections.Generic.List{System.Double},System.Collections.Generic.List{System.Double},System.Double,System.Int32,System.Boolean)">
            <summary>
            Performs dynamic relaxation on a structure of lines
            BuroHappold
            </summary>
            <param name="lines"></param>
            <param name="lockedPoints"></param>
            <param name="gravity"></param>
            <param name="barStiffnesses"></param>
            <param name="lengthMultiplier"></param>
            <param name="treshold"></param>
            <param name="maxNoIt"></param>
            <param name="run"></param>
            <returns></returns>
            <search>BH, dynamic relaxation, formfind, relax</search>
            
        </member>
    </members>
</doc>
