<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Basilisk</name>
    </assembly>
    <members>
        <member name="T:Geometry.Vector">
            <summary>
            BHoM Vector object
            </summary>
        </member>
        <member name="M:Geometry.Vector.FromDSVector(Autodesk.DesignScript.Geometry.Vector)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Vector.ToDSVector(BHoM.Geometry.Vector)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Vector.ToJSON(BHoM.Geometry.Vector)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Vector.FromJSON(System.String)">
            <summary></summary>
        </member>
        <member name="T:Geometry.Plane">
            <summary>
            BHoM Plane object
            </summary>
        </member>
        <member name="M:Geometry.Plane.FromDSPlane(Autodesk.DesignScript.Geometry.Plane)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Plane.ToDSPlane(BHoM.Geometry.Plane)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Plane.ToJSON(BHoM.Geometry.Plane)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Plane.FromJSON(System.String)">
            <summary></summary>
        </member>
        <member name="T:Geometry.Point">
            <summary>
            BHoM Point object
            </summary>
        </member>
        <member name="M:Geometry.Point.FromDSPoint(Autodesk.DesignScript.Geometry.Point)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Point.ToDSPoint(BHoM.Geometry.Point)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Point.ToJSON(BHoM.Geometry.Point)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Point.FromJSON(System.String)">
            <summary></summary>
        </member>
        <member name="T:Geometry.Line">
            <summary>
            BHoM Line object
            </summary>
        </member>
        <member name="M:Geometry.Line.FromDSLine(Autodesk.DesignScript.Geometry.Line)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Line.FromDSPoints(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Line.ToDSLine(BHoM.Geometry.Line)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Line.ToJSON(BHoM.Geometry.Line)">
            <summary></summary>
        </member>
        <member name="M:Geometry.Line.FromJSON(System.String)">
            <summary></summary>
        </member>
        <member name="T:Global.BHoM_Object">
            <summary>
            BHoM Object
            </summary>
        </member>
        <member name="M:Global.BHoM_Object.SetPropertyValueByName(System.Object,System.String,System.Object)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.GetPropertyValueByName(System.Object,System.String)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.GetPropertyNames(System.Object)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.ToJSON(System.Object)">
            <summary></summary>
        </member>
        <member name="M:Global.BHoM_Object.FromJSON(System.String)">
            <summary></summary>
        </member>
        <member name="T:Structural.Bar">
            <summary>
            Structural tools
            BuroHappold
            <class name="BHGeometryTools">Geometry tools for Dynamo</class>
            </summary>
        </member>
        <member name="M:Structural.Bar.FromNodes(BHoM.Structural.Node,BHoM.Structural.Node)">
            <summary></summary>
        </member>
        <member name="T:Structural.Node">
            <summary></summary>
        </member>
        <member name="M:Structural.Node.FromDSPoint(Autodesk.DesignScript.Geometry.Point)">
            <summary></summary>
        </member>
    </members>
</doc>
